version: 2
updates:
  - package-ecosystem: "julia"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "julia"

  - package-ecosystem: "julia"
    directory: "/docs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:15"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docs"
      - "julia"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
