name = "VortexMethod"
uuid = "d0bfb0ea-6286-496d-8bb4-f6dc2a72891a"
authors = ["Subhajit Kar <subhajitkar19@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
